### ISSUE TITLE
view on mobile

### ISSUE THREAD

**Issue by nicodel** [maboiteaspam/ma-clef-usb#1]
When seen on a mobile, the top bar is hiding the navigation.

Screenshots better than words....
![2015-01-31-16-06-32](https://cloud.githubusercontent.com/assets/1799460/5988529/8b25e20a-a964-11e4-9c45-1798cbb8db32.png)

**Comment by maboiteaspam** [comment]
yes, it is not in the plan to promote it files is much better. It was more a playground to me. But if you feel like it worth to be done please go ahead fork it, publish it !
