### ISSUE TITLE
Can't run ma-clef-usb with the -h option. The host is still 127.0.0.1 

### ISSUE THREAD

**Issue by cyril-mamai** [maboiteaspam/ma-clef-usb#2]
Hello, I have tried to launch the standalone ma-clef-usb with the -h option for external access. Without any luck. I have tried -h with external IP and with the hostname and with FQDN. The application always launched with the 127.0.0.1. I've checked I can wget the index.html from 127.0.0.1. So app is works. Any ideas?

**Comment by maboiteaspam** [comment]
Hi,

thanks for report, indeed there was an issue there, it s fixed. 
I also published the package on npm and improved ffmpeg transcode to catch its fatal errors.

But seems like there is more job to do there to properly stream to the end front.
It would need to compare and inspire of meloncholy/vid-streamer module.
